server:
  port: 8765
spring:
  application:
    name: eureka-feign-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#配置熔断器hystrix
feign:
  hystrix:
    enabled: true