server:
  port: 8080
spring:
    application:
        name: demo-order
    datasource:
        url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
