server:
  port: 8080
spring:
    application:
        name: demo-order
    datasource:
#        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF8
#        driver-class-name: com.mysql.jdbc.Driver
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
#        url: jdbc:mysql://192.168.91.4:3306/pms?useUnicode=true&characterEncoding=utf8
        username: root
        password: root

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
